// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KDQDG9MPxZtx8Sqp9pYb0jWeLEFMVGY',
    appId: '1:776341121538:web:b7d673cb0036c2e080d51b',
    messagingSenderId: '776341121538',
    projectId: 'freelance-app-d6c32',
    authDomain: 'freelance-app-d6c32.firebaseapp.com',
    storageBucket: 'freelance-app-d6c32.firebasestorage.app',
    measurementId: 'G-C9JD0QDD22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkX_UrSv9ZanrNSITIJe_BgQrVXFhiw4',
    appId: '1:776341121538:android:e5009625904bb85d80d51b',
    messagingSenderId: '776341121538',
    projectId: 'freelance-app-d6c32',
    storageBucket: 'freelance-app-d6c32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ1cQZTWdeChOsD35RuQQ7qXttZ2mBbCE',
    appId: '1:776341121538:ios:ee799f2c5806bda180d51b',
    messagingSenderId: '776341121538',
    projectId: 'freelance-app-d6c32',
    storageBucket: 'freelance-app-d6c32.firebasestorage.app',
    iosBundleId: 'com.example.freelance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ1cQZTWdeChOsD35RuQQ7qXttZ2mBbCE',
    appId: '1:776341121538:ios:ee799f2c5806bda180d51b',
    messagingSenderId: '776341121538',
    projectId: 'freelance-app-d6c32',
    storageBucket: 'freelance-app-d6c32.firebasestorage.app',
    iosBundleId: 'com.example.freelance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KDQDG9MPxZtx8Sqp9pYb0jWeLEFMVGY',
    appId: '1:776341121538:web:deb98b7c19dfa8da80d51b',
    messagingSenderId: '776341121538',
    projectId: 'freelance-app-d6c32',
    authDomain: 'freelance-app-d6c32.firebaseapp.com',
    storageBucket: 'freelance-app-d6c32.firebasestorage.app',
    measurementId: 'G-GF793CC183',
  );
}
